### ISSUE TITLE
npm packages missing

### ISSUE THREAD

**Issue by oddbytes** [hogarthww-labs/amplify-category-sqs-lambda#2]
Hello!

I'm trying to add a SQS queue and lambda triggered function to my amplify project and I have found your plugins. I see npm packages are missing, and don't know how to integrate the source code.... could you please advise?

Thanks!

**Comment by hogarthww-labs** [comment]
This package and the other ones on this account are all "experimental" to be used as a starting point to "roll your own". 
When I developed them I had little knowledge of AWS cloud formation templates. I recommend you clone the repo and go from there. 

Not sure what you mean by "npm packages are missing" - in any case you would have to run `npm install` or `yarn` to install the npm packages.

**Comment by oddbytes** [comment]
Hi!

I meant that there is no published npm package for this project (amplify-category-sqs-lambda). I have downloaded the source code and played around a bit with it,  and although i have finally added the sqs queue manually to my amplify project , your code has given me a clear idea about how an amplify plugin works.  Thanks!

**Comment by hogarthww-labs** [comment]
Ah yeah, there is no npm package because I've never gotten around to actually test it and I don't want to publish a package that I haven't tested. Glad it worked for you :)

**Comment by hogarthww-labs** [comment]
I updated the `Readme` with notes that make it clear it has not yet been published to npm.
